# Generated by Django 2.2.2 on 2020-03-12 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(null=True)),
                ('summary', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(null=True, upload_to='pictures/')),
                ('avg_budget', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('reviews', models.CharField(blank=True, max_length=255, null=True)),
                ('no_running_services', models.IntegerField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('job_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('pictures', models.ImageField(null=True, upload_to='pictures/')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('base_charge_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('provider_arrival', models.DateTimeField(blank=True, null=True)),
                ('before_pictures', models.ImageField(null=True, upload_to='pictures/')),
                ('after_pictures', models.ImageField(null=True, upload_to='pictures/')),
                ('part_replacement_required', models.BooleanField(default=False)),
                ('provider_job_cost', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('agree_job_cost', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('user_provided_cost', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('provider_complete_job', models.BooleanField(default=False)),
                ('user_signoff_on_job', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('job_category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Jobs.JobCategory')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
