# Generated by Django 2.2.2 on 2020-03-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjob',
            name='status',
            field=models.CharField(blank=True, choices=[('complete', 'complete'), ('in-progress', 'in-progress'), ('rejected', 'rejected'), ('Not-started', 'Not-started')], default='Not-started', max_length=255),
        ),
    ]
