# Generated by Django 2.2.2 on 2020-03-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_auto_20200314_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjob',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
