# Generated by Django 2.2.2 on 2020-03-18 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_auto_20200318_0900'),
        ('Jobs', '0004_jobmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('bid_status', models.CharField(blank=True, max_length=255, null=True)),
                ('availability_time', models.DateTimeField(blank=True, null=True)),
                ('base_amount_charged', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Jobs.UserJob')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Auth.Profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
