# Generated by Django 2.2.2 on 2020-03-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0005_bids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcategory',
            old_name='avg_budget',
            new_name='total_transactions_amount',
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='no_providers',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
