# Generated by Django 2.2.2 on 2020-03-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0006_auto_20200326_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='no_providers',
            field=models.IntegerField(blank=True),
        ),
    ]
