# Generated by Django 2.2.2 on 2020-03-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0007_auto_20200326_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjob',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
