# Generated by Django 2.2.2 on 2020-08-17 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0009_auto_20200815_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='management_label',
            field=models.CharField(blank=-1, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='manager_name',
            field=models.CharField(blank=-1, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='manager_phone_no',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
