# Generated by Django 2.2.2 on 2020-03-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0014_auto_20200325_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Deals',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
