# Generated by Django 2.2.2 on 2020-03-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0015_auto_20200327_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Deals',
            field=models.IntegerField(blank=True),
        ),
    ]
