# Generated by Django 2.2.2 on 2020-04-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0019_auto_20200401_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='details',
            field=models.TextField(null=True),
        ),
    ]
