# Generated by Django 2.2.2 on 2020-04-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0020_profile_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Deals',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
