# Generated by Django 2.2.2 on 2020-04-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0021_auto_20200405_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Deals',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
